### ISSUE TITLE
Wiiu builds fail to load assets/Overlays

### ISSUE THREAD

**Issue by ruijtunes** [libretro/beetle-pce-fast-libretro#200]
After the changes from October 2,  all mednafen_pce cores fail to load assets/Overlays.
Tested on Wiiu.

**Comment by hizzlekizzle** [comment]
That should be fixed now. Try the 1.9.13.2 build.

**Comment by ruijtunes** [comment]
I just test with the latest build and the problem stays the same.

**Comment by hizzlekizzle** [comment]
Does this one treat you any better? http://buildbot.libretro.com/nightly/nintendo/wiiu/2021-11-13_RetroArch.7z

**Comment by ruijtunes** [comment]
I tested it with this release and it still doesn't show any overlay and the menu is missing all the Assets. I don't know if I'm explaining myself well, all cores work perfectly except PCE, PCE Fast and Supergrafx. These worked perfectly until the changes made on the 2nd of October.

 Commits on Oct 2, 2021
Remove unused file
@twinaphex
twinaphex committed on 2 Oct
 
slim down on zlib
@twinaphex
twinaphex committed on 2 Oct

The problem has to be with these changes.

**Comment by Ploggy** [comment]
Happens to me too, I manually updated assets just to be sure..
![20211124_112823](https://user-images.githubusercontent.com/1160255/143232544-420f805d-dce4-4b7c-8791-3e692705c5be.jpg)

**Comment by gblues** [comment]
hey @Ploggy can you try the latest nightly? It looks like there were a couple zlib-related commits that went in about the time you posted this and I have no idea if the version you're using includes those commits or not.

If this still happens, @twinaphex this is probably the zlib changes--libpng and zlib are intertwined with each other and so the zlib code you cut out may have quietly broken PNG processing which would account for the garbled assets.

**Comment by gblues** [comment]
I just did a manual nightly build and the assets look OK.

**Comment by ruijtunes** [comment]
I just tested with the latest build on buildbot and everything is still the same (no assets and no overlays). Tested on WiiU. I think that until the changes made on 2 October are reversed this core will fail to load the assets. Anyway, can you share your build?

**Comment by Ploggy** [comment]
@gblues Sorry for late reply.. Same here, Assets still don't display correctly. I waited long enough for your changes to hit the buildbot..

**Comment by vaguerant** [comment]
Just made a PR #202 which reverts some zlib changes to get the assets working again. As I said in the PR, that's a pretty dramatic approach to fixing whatever went wrong here, so don't be surprised if it doesn't get merged.

In the meantime, here's a current build with that PR applied if it's useful to anybody.
[mednafen_pce_fast_libretro.zip](https://github.com/libretro/beetle-pce-fast-libretro/files/7669940/mednafen_pce_fast_libretro.zip)

**Comment by Ploggy** [comment]
Nice :) Thanks.
